# Generated by Django 3.1.5 on 2021-01-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savemdip',
            fields=[
                ('em_codigo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('em_razsoc', models.CharField(blank=True, max_length=40, null=True)),
                ('em_fanta', models.CharField(blank=True, max_length=16, null=True)),
                ('em_endereco', models.CharField(blank=True, max_length=40, null=True)),
                ('em_bairro', models.CharField(blank=True, max_length=20, null=True)),
                ('em_cidade', models.CharField(blank=True, max_length=20, null=True)),
                ('em_estado', models.CharField(blank=True, max_length=2, null=True)),
                ('em_cep', models.IntegerField(blank=True, null=True)),
                ('em_cgc', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('em_inscr', models.CharField(blank=True, max_length=15, null=True)),
                ('em_jucesp', models.IntegerField(blank=True, null=True)),
                ('em_data', models.IntegerField(blank=True, null=True)),
                ('em_ddd', models.SmallIntegerField(blank=True, null=True)),
                ('em_telefone', models.IntegerField(blank=True, null=True)),
                ('em_fax', models.IntegerField(blank=True, null=True)),
                ('em_digin', models.SmallIntegerField(blank=True, null=True)),
                ('em_qtdig', models.SmallIntegerField(blank=True, null=True)),
                ('em_palav', models.CharField(blank=True, max_length=12, null=True)),
                ('em_senha', models.IntegerField(blank=True, null=True)),
                ('em_tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('em_endnum', models.IntegerField(blank=True, null=True)),
                ('em_release_log', models.SmallIntegerField(blank=True, null=True)),
                ('em_release_param', models.SmallIntegerField(blank=True, null=True)),
                ('em_pais', models.CharField(blank=True, max_length=2, null=True)),
                ('em_filler', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'savemdip',
                'managed': False,
            },
        ),
    ]
